# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ce5fe583e742b538ca08e8e43c4399a839a10d7430cf23f22fd290891631604acdd4c25fa5f0fd0701eb0df725c30763b214f36b25b6806d97f7a6d339026f

test:
  secret_key_base: e163fa26b88940221cd8ed72226f4293e3e7a13146c15f8247458d1fbfe2c7eeb46fd84086410b30ef31f7d4b7a1e87309e07514dd5f644a3f6be1f9e3dc808e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
